# Generated by Django 5.1.7 on 2025-03-21 22:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='NewArrivals',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('product', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='new_arrivals', to='products.product', verbose_name='Product')),
            ],
            options={
                'verbose_name': 'New Arrival Product',
                'verbose_name_plural': 'New Arrival Products',
                'ordering': ['-created_at'],
            },
        ),
    ]
